import { StyleSheet, Platform } from "react-native";
import Constants from "expo-constants";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8FAFC",
    paddingTop: Platform.OS === "android" ? Constants.statusBarHeight : 0,
  },
  notification: {
    position: "absolute",
    top: 50,
    left: 15,
    right: 15,
    padding: 12,
    borderRadius: 15,
    zIndex: 100,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    borderWidth: 1,
  },
  errorNotification: {
    backgroundColor: "rgba(220, 38, 38, 0.2)",
    borderColor: "rgba(220, 38, 38, 0.4)",
  },
  successNotification: {
    backgroundColor: "rgba(16, 185, 129, 0.2)",
    borderColor: "rgba(16, 185, 129, 0.4)",
  },
  notificationText: {
    color: "#1E293B",
    fontSize: 14,
    fontWeight: "600",
    textAlign: "center",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(226, 232, 240, 0.8)",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  headerTitleContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1E293B",
    marginRight: 5,
  },
  headerFilterIndicator: {
    alignItems: "center",
    justifyContent: "center",
  },
  backButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: "#F1F5F9",
    borderWidth: 1,
    borderColor: "rgba(226, 232, 240, 0.8)",
  },
  addButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: "#F1F5F9",
    borderWidth: 1,
    borderColor: "rgba(226, 232, 240, 0.8)",
  },
  filterDropdown: {
    position: "absolute",
    top: 80,
    left: 15,
    right: 15,
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    padding: 5,
    marginTop: 5,
    borderWidth: 1,
    borderColor: "rgba(226, 232, 240, 0.8)",
    zIndex: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
  },
  filterOption: {
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderRadius: 8,
  },
  activeFilterOption: {
    backgroundColor: "rgba(67, 97, 238, 0.1)",
  },
  filterOptionText: {
    color: "#1E293B",
    fontSize: 16,
    fontWeight: "500",
  },
  activeFilterOptionText: {
    color: "#4361EE",
    fontWeight: "600",
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#1E293B",
  },
  profileButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: "#F1F5F9",
    borderWidth: 1,
    borderColor: "rgba(226, 232, 240, 0.8)",
  },
  content: {
    flex: 1,
    padding: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1E293B",
    marginBottom: 16,
  },
  featureCards: {
    flexDirection: "column",
    gap: 16,
  },
  featureCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 20,
    shadowColor: "#4361EE",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: "rgba(226, 232, 240, 0.8)",
  },
  iconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
  },
  featureTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1E293B",
    marginBottom: 8,
  },
  featureDescription: {
    fontSize: 14,
    color: "#64748B",
    lineHeight: 20,
  },
  intentionList: {
    padding: 15,
    paddingBottom: 100,
  },
  cardGradient: {
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(203, 213, 225, 0.5)",
  },
  intentionCard: {
    borderRadius: 16,
    overflow: "hidden",
    marginBottom: 16,
    shadowColor: "#4361EE",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  intentionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  intentionAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "rgba(67, 97, 238, 0.1)",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 14,
    borderWidth: 1,
    borderColor: "rgba(67, 97, 238, 0.2)",
  },
  intentionHeaderText: {
    flex: 1,
  },
  intentionAuthor: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1E293B",
    marginBottom: 4,
  },
  authorTag: {
    fontStyle: "italic",
    color: "#64748B",
  },
  intentionMeta: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  intentionTypeTag: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#EEF2FF",
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 10,
    marginRight: 8,
    borderWidth: 1,
    borderColor: "rgba(67, 97, 238, 0.2)",
  },
  intentionTypeText: {
    color: "#4361EE",
    fontSize: 12,
    marginLeft: 4,
    fontWeight: "600",
  },
  intentionTime: {
    color: "#64748B",
    fontSize: 12,
  },
  churchTag: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#EEF2FF",
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 10,
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: "rgba(67, 97, 238, 0.2)",
  },
  churchTagText: {
    color: "#4361EE",
    fontSize: 12,
    marginLeft: 5,
    fontWeight: "600",
  },
  intentionContent: {
    backgroundColor: "rgba(255, 255, 255, 0.8)",
    borderRadius: 12,
    padding: 12,
    marginVertical: 10,
    borderWidth: 1,
    borderColor: "rgba(226, 232, 240, 0.8)",
  },
  intentionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1E293B",
    marginBottom: 8,
  },
  intentionDescription: {
    fontSize: 14,
    color: "#334155",
    lineHeight: 22,
  },
  intentionActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
    flexWrap: "wrap",
  },
  intentionAction: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.8)",
    borderWidth: 1,
    borderColor: "rgba(226, 232, 240, 0.8)",
    marginRight: 8,
    marginBottom: 8,
  },
  intentionActionActive: {
    backgroundColor: "rgba(233, 150, 122, 0.1)",
    borderColor: "rgba(233, 150, 122, 0.3)",
  },
  likeButtonContainer: {
    position: "relative",
    width: 24,
    height: 24,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 4,
  },
  likeRipple: {
    position: "absolute",
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "rgba(233, 150, 122, 0.3)",
  },
  actionText: {
    color: "#64748B",
    fontSize: 14,
    fontWeight: "600",
  },
  actionTextActive: {
    color: "#E9967A",
  },
  commentsSection: {
    marginTop: 15,
  },
  commentsDivider: {
    height: 1,
    backgroundColor: "rgba(226, 232, 240, 0.8)",
    marginVertical: 10,
  },
  commentsList: {
    paddingVertical: 10,
  },
  commentsLoading: {
    marginVertical: 10,
  },
  commentItem: {
    backgroundColor: "rgba(255, 255, 255, 0.8)",
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "rgba(226, 232, 240, 0.8)",
  },
  commentHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  commentAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(67, 97, 238, 0.1)",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
    borderWidth: 1,
    borderColor: "rgba(67, 97, 238, 0.2)",
  },
  commentUser: {
    flex: 1,
  },
  commentUserName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1E293B",
  },
  commentTime: {
    fontSize: 12,
    color: "#64748B",
  },
  commentContent: {
    fontSize: 14,
    color: "#334155",
    lineHeight: 20,
  },
  emptyComments: {
    padding: 10,
    alignItems: "center",
  },
  emptyCommentsText: {
    color: "#64748B",
    fontSize: 14,
  },
  addCommentContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
    backgroundColor: "rgba(255, 255, 255, 0.8)",
    borderRadius: 25,
    padding: 8,
    borderWidth: 1,
    borderColor: "rgba(226, 232, 240, 0.8)",
  },
  commentInput: {
    flex: 1,
    backgroundColor: "#F1F5F9",
    borderRadius: 20,
    paddingHorizontal: 15,
    paddingVertical: 10,
    color: "#1E293B",
    marginRight: 10,
    maxHeight: 80,
    fontSize: 14,
    borderWidth: 1,
    borderColor: "rgba(226, 232, 240, 0.8)",
  },
  sendButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#EEF2FF",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(67, 97, 238, 0.2)",
  },
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    padding: 40,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(226, 232, 240, 0.8)",
    marginTop: 20,
  },
  emptyStateText: {
    color: "#64748B",
    fontSize: 16,
    textAlign: "center",
    marginTop: 16,
    marginBottom: 24,
  },
  emptyStateButton: {
    backgroundColor: "#4361EE",
    borderRadius: 30,
    paddingVertical: 12,
    paddingHorizontal: 24,
  },
  emptyStateButtonText: {
    color: "#FFFFFF",
    fontWeight: "600",
    fontSize: 16,
  },
  churchCard: {
    borderRadius: 16,
    overflow: "hidden",
    marginBottom: 16,
    shadowColor: "#4361EE",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  churchInfo: {
    flex: 1,
  },
  churchName: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1E293B",
    marginBottom: 4,
  },
  churchDescription: {
    fontSize: 14,
    color: "#334155",
    marginBottom: 16,
    lineHeight: 20,
  },
  churchStats: {
    flexDirection: "row",
    marginBottom: 16,
  },
  statItem: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 16,
  },
  statText: {
    fontSize: 14,
    color: "#64748B",
    marginLeft: 6,
  },
  cardActions: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  viewButton: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    backgroundColor: "#F1F5F9",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(226, 232, 240, 0.8)",
    flex: 1,
    marginRight: 8,
    alignItems: "center",
  },
  viewButtonText: {
    color: "#64748B",
    fontWeight: "600",
    fontSize: 14,
  },
  intentionsButton: {
    flexDirection: "row",
    paddingVertical: 10,
    paddingHorizontal: 16,
    backgroundColor: "#4361EE",
    borderRadius: 8,
    flex: 1.5,
    marginLeft: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonIcon: {
    marginRight: 8,
  },
  intentionsButtonText: {
    color: "#FFFFFF",
    fontWeight: "600",
    fontSize: 14,
  },
  listContainer: {
    padding: 16,
    paddingBottom: 32,
  },
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    padding: 40,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(226, 232, 240, 0.8)",
    marginTop: 20,
  },
  emptyText: {
    fontSize: 16,
    color: "#64748B",
    marginTop: 16,
    marginBottom: 20,
    textAlign: "center",
  },
  emptyButton: {
    backgroundColor: "#4361EE",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
  },
  emptyButtonText: {
    color: "#FFFFFF",
    fontWeight: "600",
    fontSize: 16,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.75)",
    justifyContent: "center",
    paddingVertical: 20,
  },
  modalScrollView: {
    maxHeight: "90%",
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 20,
    margin: 20,
    maxHeight: "90%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  confirmModalContent: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 20,
    margin: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1E293B",
    marginBottom: 20,
  },
  modalText: {
    fontSize: 16,
    color: "#334155",
    marginBottom: 24,
    textAlign: "center",
  },
  formGroup: {
    marginBottom: 20,
  },
  formLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#64748B",
    marginBottom: 8,
  },
  pickerContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 10,
  },
  typeOption: {
    flex: 1,
    minWidth: "30%",
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(226, 232, 240, 0.8)",
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    marginBottom: 8,
  },
  selectedTypeOption: {
    backgroundColor: "#EEF2FF",
    borderColor: "rgba(67, 97, 238, 0.4)",
  },
  typeOptionText: {
    color: "#334155",
    fontSize: 14,
    fontWeight: "500",
  },
  formInput: {
    backgroundColor: "#F1F5F9",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(226, 232, 240, 0.8)",
    color: "#1E293B",
    padding: 12,
    fontSize: 16,
  },
  formTextarea: {
    backgroundColor: "#F1F5F9",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(226, 232, 240, 0.8)",
    color: "#1E293B",
    padding: 12,
    height: 120,
    fontSize: 16,
    textAlignVertical: "top",
  },
  formTextareaFocused: {
    height: 200,
    borderColor: "rgba(67, 97, 238, 0.4)",
  },
  textInputContainer: {
    position: "relative",
  },
  closeButton: {
    position: "absolute",
    right: 10,
    top: 10,
    backgroundColor: "#EEF2FF",
    borderRadius: 20,
    width: 36,
    height: 36,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(67, 97, 238, 0.2)",
  },
  dropdown: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: "#F1F5F9",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(226, 232, 240, 0.8)",
  },
  dropdownText: {
    color: "#1E293B",
    fontSize: 16,
  },
  dropdownContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  dropdownOptions: {
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    marginTop: 5,
    borderWidth: 1,
    borderColor: "rgba(226, 232, 240, 0.8)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  dropdownOption: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(226, 232, 240, 0.8)",
  },
  dropdownOptionContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  dropdownOptionText: {
    color: "#1E293B",
    fontSize: 16,
  },
  groupSelectorContainer: {
    marginTop: 15,
    padding: 15,
    backgroundColor: "#F8FAFC",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(226, 232, 240, 0.8)",
  },
  groupSelectorLabel: {
    color: "#1E293B",
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 10,
  },
  groupSelectorList: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  groupOption: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: "#FFFFFF",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(226, 232, 240, 0.8)",
    marginRight: 8,
    marginBottom: 8,
  },
  groupOptionSelected: {
    backgroundColor: "#EEF2FF",
    borderColor: "rgba(67, 97, 238, 0.4)",
  },
  groupOptionText: {
    color: "#1E293B",
    fontSize: 14,
    fontWeight: "500",
  },
  noGroupsText: {
    color: "#64748B",
    fontSize: 14,
    fontStyle: "italic",
    marginTop: 5,
  },
  memberSelectorContainer: {
    marginTop: 15,
    padding: 15,
    backgroundColor: "#F8FAFC",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(226, 232, 240, 0.8)",
    maxHeight: 200,
  },
  memberSelectorLabel: {
    color: "#1E293B",
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 10,
  },
  memberSelectorList: {
    maxHeight: 120,
  },
  memberOption: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: "#FFFFFF",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(226, 232, 240, 0.8)",
    marginRight: 8,
    marginBottom: 8,
    minWidth: 150,
  },
  memberOptionSelected: {
    backgroundColor: "#EEF2FF",
    borderColor: "rgba(67, 97, 238, 0.4)",
  },
  memberOptionText: {
    color: "#1E293B",
    fontSize: 14,
    fontWeight: "500",
    textAlign: "center",
  },
  noMembersText: {
    color: "#64748B",
    fontSize: 14,
    fontStyle: "italic",
    marginTop: 5,
    textAlign: "center",
  },
  churchesContainer: {
    flexDirection: "row",
    paddingVertical: 5,
  },
  churchOption: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(226, 232, 240, 0.8)",
    marginRight: 10,
  },
  churchOptionSelected: {
    backgroundColor: "#EEF2FF",
    borderColor: "rgba(67, 97, 238, 0.4)",
  },
  churchOptionText: {
    color: "#1E293B",
    fontSize: 14,
    fontWeight: "600",
  },
  accessory: {
    backgroundColor: "#F1F5F9",
    padding: 15,
    alignItems: "flex-end",
    borderTopWidth: 1,
    borderTopColor: "rgba(226, 232, 240, 0.8)",
  },
  accessoryText: {
    color: "#4361EE",
    fontSize: 16,
    fontWeight: "600",
  },
  modalActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: "#F1F5F9",
    borderRadius: 8,
    paddingVertical: 12,
    marginRight: 8,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(226, 232, 240, 0.8)",
  },
  cancelButtonText: {
    color: "#64748B",
    fontSize: 16,
    fontWeight: "600",
  },
  createButton: {
    flex: 1,
    backgroundColor: "#4361EE",
    borderRadius: 8,
    paddingVertical: 12,
    marginLeft: 8,
    alignItems: "center",
  },
  createButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  deleteButton: {
    flex: 1,
    backgroundColor: "#EF4444",
    borderRadius: 8,
    paddingVertical: 12,
    marginLeft: 8,
    alignItems: "center",
  },
  deleteButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  loadingOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.7)",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F8FAFC",
  },
  churchHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  churchIcon: {
    width: 70,
    height: 70,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
  },
  churchHeaderInfo: {
    flex: 1,
  },
  roleBadge: {
    backgroundColor: "#EEF2FF",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: "rgba(79, 70, 229, 0.2)",
  },
  roleText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#4F46E5",
  },
  contentContainer: {
    padding: 16,
  },
  infoCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
    shadowColor: "#4361EE",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: "rgba(226, 232, 240, 0.8)",
  },
  description: {
    fontSize: 14,
    color: "#334155",
    lineHeight: 22,
    marginBottom: 16,
  },
  detailItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  detailIconContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#EEF2FF",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
    borderWidth: 1,
    borderColor: "rgba(67, 97, 238, 0.2)",
  },
  detailText: {
    fontSize: 14,
    color: "#334155",
    flex: 1,
  },
  featuresTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1E293B",
    marginBottom: 16,
  },
  featuresContainer: {
    flexDirection: "column",
    gap: 16,
    marginBottom: 30,
  },
  featureCardContent: {
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(203, 213, 225, 0.5)",
  },
  featureIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "rgba(226, 232, 240, 0.8)",
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  errorText: {
    fontSize: 18,
    color: "#64748B",
    marginTop: 16,
    marginBottom: 20,
  },
  errorButton: {
    backgroundColor: "#4361EE",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
  },
  errorButtonText: {
    color: "#FFFFFF",
    fontWeight: "600",
    fontSize: 16,
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: "rgba(226, 232, 240, 0.8)",
  },
});