import { StyleSheet, Platform } from "react-native";
import theme from "../../../theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.pageBg,
  },
  gradientBackground: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    zIndex: -1,
  },
  floatingHeader: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: Platform.OS === "ios" ? 90 : 70,
    zIndex: 100,
    borderBottomWidth: 1,
    borderBottomColor: theme.divider,
    backgroundColor: "rgba(255, 255, 255, 0.85)",
    ...theme.shadowLight,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: theme.spacingL,
    paddingTop: Platform.OS === "ios" ? 40 : 16,
    paddingBottom: 10,
    backgroundColor: "rgba(255, 255, 255, 0.7)",
    zIndex: 10,
    ...theme.shadowLight,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: theme.radiusFull,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: theme.neutral100,
    ...theme.shadowLight,
    transform: [{ scale: 1 }],
  },
  ministryTitleContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: theme.spacingM,
    paddingVertical: theme.spacingS,
    borderRadius: theme.radiusMedium,
  },
  headerAvatar: {
    width: 40,
    height: 40,
    borderRadius: theme.radiusFull,
    marginRight: theme.spacingM,
    overflow: "hidden",
    backgroundColor: theme.neutral200,
    ...theme.shadowLight,
  },
  headerInfo: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: theme.fontSemiBold,
    color: theme.neutral900,
  },
  memberCount: {
    fontSize: 12,
    color: theme.neutral600,
    marginTop: 2,
  },
  infoButton: {
    width: 40,
    height: 40,
    borderRadius: theme.radiusFull,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: theme.neutral100,
    ...theme.shadowLight,
  },
  chatContainer: {
    flex: 1,
    position: "relative",
    flexDirection: "column",
  },
  messagesContainer: {
    flex: 1,
    padding: theme.spacingS,
    paddingBottom: 0,
  },
  messagesContainerWithKeyboard: {
    paddingBottom: 0,
  },
  messagesList: {
    paddingVertical: theme.spacingM,
    paddingBottom: theme.spacingXL, // Larger padding to keep last message above input
  },
  messageLoadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  messageLoadingText: {
    marginTop: theme.spacingM,
    fontSize: 16,
    color: theme.neutral600,
    fontWeight: theme.fontMedium,
  },
  emptyMessagesContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: theme.spacingXL,
  },
  emptyMessagesIcon: {
    width: 80,
    height: 80,
    borderRadius: theme.radiusFull,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: theme.spacing2XL,
    ...theme.shadowMedium,
    backgroundColor: `${theme.primary}20`,
  },
  emptyMessagesTitle: {
    fontSize: 22,
    fontWeight: theme.fontBold,
    color: theme.neutral900,
    marginBottom: theme.spacingM,
  },
  emptyMessagesSubtitle: {
    fontSize: 16,
    color: theme.neutral600,
    textAlign: "center",
    lineHeight: 22,
  },
  dateDividerContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: theme.spacingL,
    paddingHorizontal: theme.spacingL,
  },
  dateDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: theme.divider,
  },
  dateDividerTextContainer: {
    backgroundColor: theme.neutral100,
    paddingHorizontal: theme.spacingM,
    paddingVertical: theme.spacingS,
    borderRadius: theme.radiusMedium,
    marginHorizontal: theme.spacingS,
    ...theme.shadowLight,
  },
  dateDividerText: {
    fontSize: 12,
    color: theme.neutral600,
    fontWeight: theme.fontMedium,
  },
  messageContainer: {
    flexDirection: "row",
    marginVertical: 4,
    paddingHorizontal: theme.spacingS,
  },
  currentUserMessage: {
    justifyContent: "flex-end",
  },
  otherUserMessage: {
    justifyContent: "flex-start",
  },
  messageAvatar: {
    width: 34,
    height: 34,
    borderRadius: theme.radiusFull,
    marginRight: theme.spacingS,
    alignSelf: "flex-end",
    marginBottom: 6,
    ...theme.shadowLight,
  },
  userAvatarImage: {
    width: 34,
    height: 34,
    borderRadius: theme.radiusFull,
  },
  userAvatarPlaceholder: {
    width: 34,
    height: 34,
    borderRadius: theme.radiusFull,
    justifyContent: "center",
    alignItems: "center",
  },
  userAvatarInitials: {
    fontSize: 13,
    fontWeight: theme.fontBold,
    color: theme.neutral50,
  },
  messageBubble: {
    maxWidth: "80%",
    paddingHorizontal: theme.spacingL,
    paddingVertical: theme.spacingM,
    borderRadius: theme.radiusLarge,
    marginBottom: 4,
  },
  currentUserBubble: {
    backgroundColor: theme.primary,
    borderBottomRightRadius: 4,
    ...theme.shadowLight,
  },
  otherUserBubble: {
    backgroundColor: theme.neutral50,
    borderBottomLeftRadius: 4,
    ...theme.shadowLight,
  },
  sendingMessage: {
    opacity: 0.7,
  },
  errorMessage: {
    borderWidth: 1,
    borderColor: theme.error,
  },
  messageUsername: {
    fontSize: 12,
    fontWeight: theme.fontBold,
    color: theme.primary,
    marginBottom: 2,
  },
  messageText: {
    fontSize: 16,
    lineHeight: 22,
    flexShrink: 1,
  },
  currentUserMessageText: {
    color: theme.neutral50,
  },
  otherUserMessageText: {
    color: theme.neutral900,
  },
  messageFooter: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    marginTop: 2,
  },
  messageTime: {
    fontSize: 10,
    color: theme.neutral400,
  },
  currentUserMessageTime: {
    color: theme.neutral200,
  },
  messageStatus: {
    marginLeft: 4,
  },
  statusIcon: {
    marginLeft: 2,
  },
  inputAreaContainer: {
    backgroundColor: theme.neutral50,
    borderTopWidth: 1,
    borderTopColor: theme.divider,
    paddingTop: theme.spacingS,
    minHeight: 70,
    ...theme.shadowMedium,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    padding: theme.spacingS,
    paddingHorizontal: theme.spacingM,
    backgroundColor: theme.neutral50,
  },
  attachButton: {
    width: 40,
    height: 40,
    borderRadius: theme.radiusFull,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: theme.neutral100,
    ...theme.shadowLight,
  },
  messageInput: {
    flex: 1,
    backgroundColor: theme.neutral100,
    borderRadius: 24,
    paddingHorizontal: theme.spacingL,
    paddingVertical: theme.spacingM,
    maxHeight: 120,
    fontSize: 16,
    color: theme.neutral900,
    borderWidth: 1,
    borderColor: theme.divider,
    textAlignVertical: "center",
    ...theme.shadowLight,
    marginHorizontal: theme.spacingS,
  },
  sendButton: {
    width: 42,
    height: 42,
    borderRadius: theme.radiusFull,
    backgroundColor: theme.primary,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: theme.spacingS,
    ...theme.shadowLight,
  },
  sendButtonDisabled: {
    backgroundColor: theme.neutral300,
  },
  sendButtonPressed: {
    backgroundColor: theme.secondary,
    transform: [{ scale: 0.95 }],
  },
  ministryAvatarImage: {
    width: 40,
    height: 40,
    borderRadius: theme.radiusFull,
  },
  ministryAvatarPlaceholder: {
    width: 40,
    height: 40,
    borderRadius: theme.radiusFull,
    justifyContent: "center",
    alignItems: "center",
  },
  ministryAvatarInitials: {
    fontSize: 16,
    fontWeight: theme.fontBold,
    color: theme.neutral50,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: theme.pageBg,
  },
  loadingText: {
    marginTop: theme.spacingL,
    fontSize: 18,
    color: theme.neutral600,
    fontWeight: theme.fontMedium,
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: theme.spacingXL,
    backgroundColor: theme.pageBg,
  },
  errorTitle: {
    fontSize: 22,
    fontWeight: theme.fontBold,
    color: theme.neutral900,
    marginTop: theme.spacingL,
    marginBottom: theme.spacingS,
  },
  errorText: {
    fontSize: 16,
    color: theme.neutral600,
    textAlign: "center",
    marginBottom: theme.spacing2XL,
  },
  errorButton: {
    backgroundColor: theme.primary,
    paddingHorizontal: theme.spacing2XL,
    paddingVertical: theme.spacingM,
    borderRadius: theme.radiusLarge,
    ...theme.shadowMedium,
  },
  errorButtonText: {
    color: theme.neutral50,
    fontSize: 16,
    fontWeight: theme.fontSemiBold,
  },
  // Style for the loading more indicator at the top
  loadMoreHeader: {
    padding: theme.spacingL,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    backgroundColor: `${theme.primary}10`,
    borderRadius: theme.radiusMedium,
    margin: theme.spacingS,
  },
  loadMoreText: {
    marginLeft: theme.spacingS,
    fontSize: 14,
    color: theme.neutral600,
  },
  ministryInfoPanel: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    width: "85%",
    backgroundColor: theme.neutral50,
    zIndex: 1000,
    ...theme.shadowHeavy,
  },
  ministryInfoContainer: {
    flex: 1,
    width: "100%",
    height: "100%",
  },
  ministryInfoHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: theme.spacingL,
    paddingTop: Platform.OS === "ios" ? 50 : 16,
    paddingBottom: theme.spacingM,
    borderBottomWidth: 1,
    borderBottomColor: theme.divider,
  },
  closeInfoButton: {
    padding: theme.spacingS,
  },
  ministryInfoTitle: {
    flex: 1,
    marginLeft: theme.spacingS,
    fontSize: 18,
    fontWeight: theme.fontSemiBold,
    color: theme.neutral900,
    textAlign: "center",
  },
  ministryInfoContent: {
    flex: 1,
    padding: theme.spacing2XL,
    alignItems: "center",
  },
  ministryInfoAvatar: {
    width: 80,
    height: 80,
    borderRadius: theme.radiusFull,
    marginBottom: theme.spacingL,
    ...theme.shadowMedium,
  },
  ministryInfoName: {
    fontSize: 24,
    fontWeight: theme.fontBold,
    color: theme.neutral900,
    textAlign: "center",
    marginBottom: theme.spacingS,
  },
  ministryInfoMembers: {
    fontSize: 16,
    color: theme.neutral600,
    marginBottom: theme.spacing2XL,
  },
  ministryInfoDescriptionContainer: {
    width: "100%",
    padding: theme.spacingL,
    backgroundColor: theme.neutral100,
    borderRadius: theme.radiusLarge,
    marginBottom: theme.spacing3XL,
    ...theme.shadowLight,
  },
  ministryInfoDescriptionTitle: {
    fontSize: 16,
    fontWeight: theme.fontSemiBold,
    color: theme.primary,
    marginBottom: theme.spacingS,
  },
  ministryInfoDescription: {
    fontSize: 15,
    color: theme.neutral700,
    lineHeight: 22,
  },
  leaveMinistryButton: {
    paddingHorizontal: theme.spacing2XL,
    paddingVertical: theme.spacingM,
    backgroundColor: `${theme.error}20`,
    borderRadius: theme.radiusLarge,
    borderWidth: 1,
    borderColor: `${theme.error}40`,
  },
  leaveMinistryButtonText: {
    fontSize: 16,
    fontWeight: theme.fontSemiBold,
    color: theme.error,
  },
  // New UI elements
  typingIndicator: {
    position: "absolute",
    top: 10,
    left: 0,
    right: 0,
    zIndex: 100,
    alignItems: "center",
    justifyContent: "center",
  },
  typingBubble: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: `${theme.primary}15`,
    paddingHorizontal: theme.spacingL,
    paddingVertical: theme.spacingS,
    borderRadius: theme.radiusLarge,
    ...theme.shadowLight,
    width: 150,
  },
  typingText: {
    fontSize: 14,
    color: theme.primary,
    fontWeight: theme.fontMedium,
    marginRight: theme.spacingS,
  },
  // All messages loaded indicator
  allMessagesLoadedContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: theme.spacingM,
    paddingHorizontal: theme.spacingL,
    marginVertical: theme.spacingM,
    backgroundColor: `${theme.success}10`,
    borderRadius: theme.radiusMedium,
    alignSelf: "center",
  },
  allMessagesLoadedText: {
    fontSize: 14,
    color: theme.success,
    fontWeight: theme.fontMedium,
  },
  // Debug styles
  debugInfoContainer: {
    padding: 8,
    backgroundColor: "#333",
    margin: 4,
    borderRadius: 4,
  },
  debugInfoText: {
    color: "#fff",
    fontSize: 10,
  },
});
