import { StyleSheet, Dimensions } from "react-native";
import { THEME } from "./theme";

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: THEME.background,
  },
  safeArea: {
    backgroundColor: THEME.background,
    zIndex: 1,
  },
  header: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    backgroundColor: THEME.background,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: THEME.border,
  },
  scrollContent: {
    paddingTop: 0,
    paddingBottom: 80,
  },
  heroSection: {
    marginHorizontal: 20,
    marginVertical: 16,
    borderRadius: 16,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
  },
  mainContainer: {
    backgroundColor: THEME.background,
  },
  // Header
  headerTitle: {
    fontSize: 26,
    fontWeight: "700",
    color: THEME.primary,
  },
  headerButtons: {
    flexDirection: "row",
    alignItems: "center",
  },
  headerButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: THEME.background,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 8,
  },
  // Search
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 20,
    marginTop: 8,
    marginBottom: 12,
    backgroundColor: THEME.card,
    borderRadius: 12,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: THEME.border,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    height: 48,
    fontSize: 16,
    color: THEME.primary,
  },
  clearSearchButton: {
    padding: 8,
  },
  // View Selector
  viewSelector: {
    flexDirection: "row",
    marginHorizontal: 20,
    marginBottom: 16,
    backgroundColor: THEME.card,
    borderRadius: 30,
    padding: 4,
    shadowColor: THEME.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  viewOption: {
    flex: 1,
    flexDirection: "row",
    paddingVertical: 10,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 25,
  },
  viewOptionActive: {
    backgroundColor: THEME.buttonPrimary,
  },
  viewOptionText: {
    fontSize: 16,
    fontWeight: "600",
    color: THEME.secondary,
    marginLeft: 6,
  },
  viewOptionTextActive: {
    color: THEME.buttonText,
  },
  // Month Navigation
  monthNavigation: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  monthNavArrow: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: THEME.card,
    shadowColor: THEME.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  monthText: {
    fontSize: 18,
    fontWeight: "600",
    color: THEME.primary,
  },
  // Calendar
  calendarContainer: {
    backgroundColor: THEME.card,
    borderRadius: 16,
    marginHorizontal: 20,
    padding: 16,
    shadowColor: THEME.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  dayLabelsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
    paddingHorizontal: 4,
  },
  dayLabelContainer: {
    width: 38,
    alignItems: "center",
  },
  dayLabel: {
    fontSize: 14,
    color: THEME.secondary,
    fontWeight: "600",
  },
  calendarGrid: {},
  calendarWeek: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  calendarDay: {
    width: 38,
    height: 60,
    alignItems: "center",
    paddingTop: 6,
    borderRadius: 10,
  },
  calendarDayOtherMonth: {
    opacity: 0.5,
  },
  calendarDaySelected: {
    backgroundColor: "#F0F0F5",
  },
  dayNumberContainer: {
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
  },
  todayContainer: {
    backgroundColor: "#EEEEF5",
  },
  selectedDayNumberContainer: {
    backgroundColor: THEME.buttonPrimary,
  },
  dayNumber: {
    fontSize: 16,
    color: THEME.primary,
    fontWeight: "500",
  },
  dayNumberOtherMonth: {
    color: THEME.light,
  },
  todayNumber: {
    color: THEME.buttonPrimary,
    fontWeight: "700",
  },
  selectedDayNumber: {
    color: THEME.buttonText,
    fontWeight: "700",
  },
  eventIndicatorContainer: {
    flexDirection: "row",
    marginTop: 4,
    justifyContent: "center",
    maxWidth: 32,
    flexWrap: "wrap",
  },
  eventIndicator: {
    width: 6,
    height: 6,
    borderRadius: 3,
    margin: 1,
  },
  multipleEventsIndicator: {
    backgroundColor: THEME.buttonPrimary,
    borderRadius: 10,
    paddingHorizontal: 5,
    paddingVertical: 1,
  },
  multipleEventsText: {
    color: THEME.buttonText,
    fontSize: 10,
    fontWeight: "700",
  },
  calendarLoading: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 50,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: THEME.secondary,
  },
  // List View
  listContainer: {
    paddingHorizontal: 20,
  },
  loadingContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 50,
  },
  noEventsContainer: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: THEME.card,
    borderRadius: 16,
    padding: 30,
    marginVertical: 20,
    shadowColor: THEME.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  noEventsText: {
    fontSize: 18,
    fontWeight: "700",
    color: THEME.primary,
    marginTop: 16,
    marginBottom: 8,
  },
  noEventsSubtext: {
    fontSize: 14,
    color: THEME.secondary,
    textAlign: "center",
    marginHorizontal: 20,
  },
  eventsList: {
    paddingVertical: 12,
  },
  // Event Cards
  eventCard: {
    backgroundColor: THEME.card,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    borderLeftWidth: 4,
    borderLeftColor: "#4299E1",
  },
  pastEventCard: {
    opacity: 0.8,
  },
  eventCardDetail: {
    marginBottom: 20,
    padding: 20,
  },
  eventHeader: {
    flexDirection: "row",
    alignItems: "center",
  },
  eventIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  eventTitleContainer: {
    flex: 1,
  },
  eventTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: THEME.primary,
    marginBottom: 4,
  },
  eventTimeLocationContainer: {
    flexDirection: "column",
  },
  dateTimeRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 2,
  },
  smallIcon: {
    marginRight: 4,
  },
  eventDateTime: {
    fontSize: 14,
    color: THEME.secondary,
  },
  locationRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  eventLocation: {
    fontSize: 14,
    color: THEME.secondary,
  },
  churchName: {
    fontSize: 12,
    color: THEME.light,
    marginLeft: 4,
  },
  eventExcerpt: {
    fontSize: 15,
    color: THEME.primary,
    lineHeight: 22,
    marginVertical: 16,
  },
  eventImageContainer: {
    height: 200,
    borderRadius: 12,
    overflow: "hidden",
    marginBottom: 16,
  },
  eventImage: {
    width: "100%",
    height: "100%",
  },
  videoLinkButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 14,
    backgroundColor: THEME.background,
    borderRadius: 12,
    marginBottom: 16,
  },
  videoLinkText: {
    marginLeft: 8,
    fontSize: 16,
    color: THEME.primary,
    fontWeight: "600",
  },
  videoThumbnail: {
    width: 120,
    height: 90,
    borderRadius: 8,
  },
  // Recurring event badge
  recurringBadge: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: THEME.accent1,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 8,
  },
  recurringInfoCard: {
    backgroundColor: THEME.accent1,
    borderRadius: 12,
    padding: 12,
    marginTop: 12,
    marginBottom: 16,
  },
  recurringInfoHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  recurringInfoTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: THEME.primary,
    marginLeft: 6,
  },
  recurringInfoText: {
    fontSize: 14,
    color: THEME.secondary,
  },
  // Edit button on card
  editButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: THEME.background,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 8,
  },
  // Event Action Row
  eventActionRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    marginTop: 8,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    marginLeft: 8,
  },
  actionButtonText: {
    fontSize: 14,
    fontWeight: "600",
    marginLeft: 6,
  },
  editActionButton: {
    backgroundColor: THEME.accent1,
  },
  editActionText: {
    color: THEME.buttonPrimary,
  },
  deleteActionButton: {
    backgroundColor: THEME.accent4,
  },
  deleteActionText: {
    color: THEME.error,
  },
  shareActionButton: {
    backgroundColor: THEME.background,
  },
  // Hero Section
  heroBackground: {
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 30,
    paddingHorizontal: 20,
  },
  iconContainer: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.3)",
  },
  heroTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: "#FFFFFF",
    textAlign: "center",
    marginBottom: 8,
  },
  heroSubtitle: {
    fontSize: 15,
    color: "rgba(255, 255, 255, 0.9)",
    textAlign: "center",
    marginBottom: 20,
    maxWidth: 300,
    lineHeight: 22,
  },
  // Add Event Button
  addEventButton: {
    flexDirection: "row",
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.3)",
  },
  addEventButtonText: {
    fontSize: 16,
    color: "#FFFFFF",
    fontWeight: "700",
    marginRight: 10,
  },
  // Date Detail Modal
  dateDetailContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: height * 0.75,
    backgroundColor: THEME.card,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingBottom: 20,
    shadowColor: THEME.shadow,
    shadowOffset: { width: 0, height: -5 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 10,
    zIndex: 99,
  },
  dateDetailHandle: {
    width: 40,
    height: 5,
    backgroundColor: THEME.border,
    borderRadius: 3,
    alignSelf: "center",
    marginTop: 10,
    marginBottom: 10,
  },
  dateDetailHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: THEME.border,
  },
  dateDetailTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: THEME.primary,
  },
  dateDetailCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: THEME.background,
    justifyContent: "center",
    alignItems: "center",
  },
  dateDetailContent: {
    flex: 1,
    padding: 20,
  },
  noEventsForDay: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 50,
  },
  noEventsForDayText: {
    fontSize: 16,
    color: THEME.secondary,
    marginTop: 16,
    marginBottom: 24,
    textAlign: "center",
  },
  addEventForDayButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: THEME.background,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: THEME.buttonPrimary,
  },
  addEventForDayText: {
    fontSize: 16,
    color: THEME.buttonPrimary,
    fontWeight: "600",
    marginRight: 8,
  },
  // Modal
  modalContainer: {
    flex: 1,
    justifyContent: "flex-end",
  },
  modalBackdrop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContent: {
    backgroundColor: THEME.card,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingBottom: 30,
    maxHeight: height * 0.9,
    shadowColor: THEME.shadow,
    shadowOffset: { width: 0, height: -10 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
  },
  modalHandle: {
    width: 40,
    height: 5,
    backgroundColor: THEME.border,
    borderRadius: 3,
    alignSelf: "center",
    marginTop: 10,
    marginBottom: 10,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: THEME.border,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: THEME.primary,
  },
  modalCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: THEME.background,
    justifyContent: "center",
    alignItems: "center",
  },
  modalForm: {
    padding: 20,
  },
  // Form Elements
  formGroup: {
    marginBottom: 20,
  },
  formLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: THEME.primary,
    marginBottom: 8,
  },
  formInput: {
    backgroundColor: THEME.background,
    borderRadius: 12,
    padding: 16,
    color: THEME.primary,
    fontSize: 16,
    borderWidth: 1,
    borderColor: THEME.border,
  },
  textAreaInput: {
    minHeight: 120,
    textAlignVertical: "top",
  },
  dateTimeButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: THEME.background,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: THEME.border,
  },
  dateTimeText: {
    color: THEME.primary,
    marginLeft: 10,
    fontSize: 16,
  },
  toggleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: THEME.background,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: THEME.border,
  },
  toggleLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: THEME.primary,
  },
  recurringContainer: {
    marginBottom: 20,
    backgroundColor: THEME.accent1,
    borderRadius: 12,
    padding: 16,
  },
  recurrenceTypeContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 8,
  },
  recurrenceTypeButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: THEME.card,
    marginRight: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: THEME.border,
  },
  recurrenceTypeButtonSelected: {
    backgroundColor: THEME.buttonPrimary,
    borderColor: THEME.buttonPrimary,
  },
  recurrenceTypeText: {
    fontSize: 14,
    color: THEME.secondary,
    fontWeight: "500",
  },
  recurrenceTypeTextSelected: {
    color: THEME.buttonText,
    fontWeight: "600",
  },
  intervalRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  intervalLabel: {
    fontSize: 16,
    color: THEME.secondary,
    marginRight: 8,
  },
  intervalInput: {
    backgroundColor: THEME.card,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    width: 60,
    borderWidth: 1,
    borderColor: THEME.border,
    marginRight: 8,
    fontSize: 16,
    color: THEME.primary,
    textAlign: "center",
  },
  intervalText: {
    fontSize: 16,
    color: THEME.secondary,
  },
  daysRow: {
    flexDirection: "row",
    marginBottom: 8,
  },
  dayButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: THEME.card,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 6,
    borderWidth: 1,
    borderColor: THEME.border,
  },
  dayButtonSelected: {
    backgroundColor: THEME.buttonPrimary,
    borderColor: THEME.buttonPrimary,
  },
  dayText: {
    fontSize: 14,
    fontWeight: "600",
    color: THEME.secondary,
  },
  dayTextSelected: {
    color: THEME.buttonText,
  },
  clearButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: THEME.accent4,
    marginTop: 8,
    alignSelf: "flex-start",
  },
  clearButtonText: {
    fontSize: 14,
    color: THEME.error,
    fontWeight: "500",
  },
  imagePickerButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    backgroundColor: THEME.background,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: THEME.buttonPrimary,
  },
  imagePickerText: {
    color: THEME.buttonPrimary,
    marginLeft: 10,
    fontSize: 16,
    fontWeight: "600",
  },
  previewImageContainer: {
    borderRadius: 12,
    overflow: "hidden",
    marginBottom: 20,
    position: "relative",
  },
  previewImage: {
    width: "100%",
    height: 180,
  },
  removeImageButton: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  submitButton: {
    backgroundColor: THEME.buttonPrimary,
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
    marginTop: 8,
    marginBottom: 16,
  },
  submitButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: THEME.buttonText,
  },
  deleteButton: {
    backgroundColor: THEME.accent4,
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
    marginBottom: 16,
  },
  deleteButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: THEME.error,
  },
  // Image Viewer Modal Styles
  imageViewerContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.9)",
  },
  imageViewerCloseButton: {
    position: "absolute",
    top: 40,
    right: 20,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 999,
  },
  fullImage: {
    width: Dimensions.get("window").width,
    height: Dimensions.get("window").height * 0.8,
  },
  // Church selector styles
  churchSelectorContainer: {
    marginVertical: 10,
  },
  selectorLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: THEME.secondary,
    marginHorizontal: 20,
    marginBottom: 8,
  },
  churchSelector: {
    paddingHorizontal: 16,
  },
  churchOption: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: THEME.background,
    marginRight: 8,
    borderWidth: 1,
    borderColor: THEME.border,
  },
  churchOptionActive: {
    backgroundColor: THEME.buttonPrimary,
    borderColor: THEME.buttonPrimary,
  },
  churchOptionText: {
    fontSize: 14,
    color: THEME.secondary,
    fontWeight: "500",
  },
  churchOptionTextActive: {
    color: THEME.buttonText,
    fontWeight: "600",
  },
  // Scrollview
  scrollView: {
    flex: 1,
  },
  scrollViewContent: {
    flexGrow: 1,
    paddingBottom: 20,
  },
  eventHost: {
    fontSize: 14,
    color: THEME.secondary,
  },
  mainContent: {
    flex: 1,
    backgroundColor: THEME.background,
  },
});
