import { StyleSheet, Dimensions } from "react-native";
import THEME from "../../../theme";

const { width, height } = Dimensions.get("window");

// Create styles with the new theme
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: THEME.pageBg,
  },
  safeArea: {
    backgroundColor: THEME.pageBg,
    zIndex: 1,
  },
  header: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    backgroundColor: THEME.pageBg,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: THEME.divider,
  },
  scrollView: {
    flex: 1,
  },
  scrollViewContent: {
    paddingTop: 0,
    paddingBottom: 80,
  },
  heroSection: {
    marginHorizontal: 20,
    marginVertical: 16,
    borderRadius: 16,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
  },
  mainContainer: {
    backgroundColor: THEME.pageBg,
  },
  // Header
  headerTitle: {
    fontSize: 26,
    fontWeight: "700",
    color: THEME.primary,
  },
  headerButtons: {
    flexDirection: "row",
    alignItems: "center",
  },
  headerButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: THEME.pageBg,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 8,
  },
  // Search
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 20,
    marginTop: 8,
    marginBottom: 12,
    backgroundColor: THEME.cardBg,
    borderRadius: 12,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: THEME.divider,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    height: 48,
    fontSize: 16,
    color: THEME.primary,
  },
  clearSearchButton: {
    padding: 8,
  },
  // View Selector
  viewSelector: {
    flexDirection: "row",
    marginHorizontal: 20,
    marginBottom: 16,
    backgroundColor: THEME.cardBg,
    borderRadius: 30,
    padding: 4,
    shadowColor: THEME.neutral800,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  viewOption: {
    flex: 1,
    flexDirection: "row",
    paddingVertical: 10,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 25,
  },
  viewOptionActive: {
    backgroundColor: THEME.primary,
  },
  viewOptionText: {
    fontSize: 16,
    fontWeight: "600",
    color: THEME.textMedium,
    marginLeft: 6,
  },
  viewOptionTextActive: {
    color: THEME.textWhite,
  },
  // Month Navigation
  monthNavigation: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  monthNavArrow: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: THEME.cardBg,
    shadowColor: THEME.neutral800,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  monthText: {
    fontSize: 18,
    fontWeight: "600",
    color: THEME.primary,
  },
  // Calendar
  calendarContainer: {
    backgroundColor: THEME.cardBg,
    borderRadius: 16,
    marginHorizontal: 20,
    padding: 16,
    shadowColor: THEME.neutral800,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  dayLabelsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
    paddingHorizontal: 4,
  },
  dayLabelContainer: {
    width: 38,
    alignItems: "center",
  },
  dayLabel: {
    fontSize: 14,
    color: THEME.textMedium,
    fontWeight: "600",
  },
  calendarGrid: {},
  calendarWeek: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  calendarDay: {
    width: 38,
    height: 60,
    alignItems: "center",
    paddingTop: 6,
    borderRadius: 10,
  },
  calendarDayOtherMonth: {
    opacity: 0.5,
  },
  calendarDaySelected: {
    backgroundColor: "#F0F0F5",
  },
  dayNumberContainer: {
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
  },
  todayContainer: {
    backgroundColor: "#EEEEF5",
  },
  selectedDayNumberContainer: {
    backgroundColor: THEME.primary,
  },
  dayNumber: {
    fontSize: 15,
    color: THEME.textDark,
    fontWeight: "400",
  },
  selectedDayNumber: {
    color: THEME.textWhite,
    fontWeight: "600",
  },
  todayNumber: {
    fontWeight: "600",
  },
  dayEventsIndicator: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 4,
  },
  eventDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    marginHorizontal: 1,
  },
  // Loading
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 40,
  },
  loadingText: {
    fontSize: 16,
    color: THEME.textMedium,
    marginTop: 10,
  },
  // Empty States
  noEventsContainer: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: THEME.cardBg,
    borderRadius: 16,
    padding: 30,
    marginVertical: 20,
    shadowColor: THEME.neutral800,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    marginHorizontal: 20,
  },
  noEventsText: {
    fontSize: 18,
    fontWeight: "600",
    color: THEME.textDark,
    marginTop: 16,
  },
  noEventsSubtext: {
    fontSize: 15,
    color: THEME.textMedium,
    textAlign: "center",
    marginTop: 8,
    maxWidth: "85%",
  },
  // List Container
  listContainer: {
    paddingTop: 8,
  },
  eventsList: {
    paddingBottom: 20,
  },
  // Event Cards
  eventCard: {
    backgroundColor: THEME.cardBg,
    borderRadius: 12,
    padding: 16,
    marginHorizontal: 20,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  eventCardHeader: {
    flexDirection: "row",
    marginBottom: 12,
  },
  eventCardImage: {
    width: 80,
    height: 80,
    borderRadius: 8,
    marginRight: 16,
  },
  eventCardContent: {
    flex: 1,
    justifyContent: "center",
  },
  eventTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: THEME.textDark,
    marginBottom: 4,
  },
  eventTime: {
    fontSize: 14,
    color: THEME.textMedium,
    marginBottom: 4,
  },
  eventLocation: {
    fontSize: 14,
    color: THEME.textMedium,
  },
  eventCardBody: {
    marginTop: 8,
  },
  eventDescription: {
    fontSize: 15,
    color: THEME.textMedium,
    lineHeight: 22,
  },
  eventCardFooter: {
    flexDirection: "row",
    marginTop: 16,
    justifyContent: "space-between",
  },
  eventMetaInfo: {
    flexDirection: "row",
    alignItems: "center",
  },
  eventActionButtons: {
    flexDirection: "row",
  },
  actionButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: THEME.pageBg,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 8,
  },
  editActionButton: {
    backgroundColor: THEME.info,
  },
  deleteActionButton: {
    backgroundColor: THEME.error,
  },
  shareActionButton: {
    backgroundColor: THEME.pageBg,
  },
  // Hero Section
  heroBackground: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  iconContainer: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "rgba(255,255,255,0.2)",
    justifyContent: "center",
    alignItems: "center",
  },
  heroTitle: {
    color: "#FFFFFF",
    fontSize: 28,
    fontWeight: "700",
    marginTop: 16,
    textAlign: "center",
  },
  heroSubtitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "400",
    opacity: 0.9,
    textAlign: "center",
    marginTop: 8,
    marginBottom: 24,
  },
  addEventButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.25)",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 24,
  },
  addEventButtonText: {
    color: "#FFFFFF",
    fontWeight: "600",
    fontSize: 16,
    marginRight: 8,
  },
  // Date Detail Modal
  dateDetailContainer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: height * 0.75,
    backgroundColor: THEME.cardBg,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingBottom: 20,
    shadowColor: THEME.neutral800,
    shadowOffset: { width: 0, height: -5 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 10,
    zIndex: 1000,
  },
  dateDetailHandle: {
    width: 40,
    height: 5,
    backgroundColor: THEME.divider,
    borderRadius: 3,
    alignSelf: "center",
    marginTop: 12,
    marginBottom: 8,
  },
  dateDetailHeader: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: THEME.divider,
  },
  dateDetailTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: THEME.textDark,
    marginBottom: 6,
  },
  dateDetailSubtitle: {
    fontSize: 15,
    color: THEME.textMedium,
  },
  dateDetailActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    paddingVertical: 8,
    paddingHorizontal: 20,
  },
  dateDetailAction: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 20,
  },
  dateDetailActionText: {
    fontSize: 14,
    fontWeight: "500",
    color: THEME.primary,
    marginLeft: 6,
  },
  dateDetailContent: {
    flex: 1,
  },
  dateDetailListItem: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: THEME.divider,
  },
  dateDetailCloseButton: {
    position: "absolute",
    top: 16,
    right: 20,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: THEME.pageBg,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
  },
  dateDetailAddButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: THEME.pageBg,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 24,
    marginHorizontal: 20,
    marginBottom: 16,
    marginTop: 8,
  },
  dateDetailAddButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: THEME.primary,
    marginLeft: 8,
  },
  // Modals
  modalContainer: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  modalBackdrop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  modalContent: {
    backgroundColor: THEME.cardBg,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingBottom: 30,
    maxHeight: height * 0.9,
    shadowColor: THEME.neutral800,
    shadowOffset: { width: 0, height: -10 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 10,
  },
  modalHandle: {
    width: 40,
    height: 5,
    backgroundColor: THEME.divider,
    borderRadius: 3,
    alignSelf: "center",
    marginTop: 12,
    marginBottom: 8,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: THEME.divider,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: THEME.textDark,
  },
  modalCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: THEME.pageBg,
    justifyContent: "center",
    alignItems: "center",
  },
  // Form Elements
  formContainer: {
    padding: 20,
  },
  formControl: {
    marginBottom: 20,
  },
  formLabel: {
    fontSize: 16,
    fontWeight: "500",
    color: THEME.textDark,
    marginBottom: 8,
  },
  formInput: {
    backgroundColor: THEME.pageBg,
    borderRadius: 12,
    padding: 16,
    color: THEME.primary,
    fontSize: 16,
    borderWidth: 1,
    borderColor: THEME.divider,
  },
  textAreaInput: {
    minHeight: 120,
    textAlignVertical: "top",
  },
  dateTimePickerButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: THEME.pageBg,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: THEME.divider,
  },
  dateTimeText: {
    fontSize: 16,
    color: THEME.textDark,
    flex: 1,
  },
  recurrenceContainer: {
    marginTop: 8,
  },
  recurrenceTypeContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 16,
  },
  recurrenceTypeButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: THEME.cardBg,
    marginRight: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: THEME.divider,
  },
  recurrenceTypeButtonSelected: {
    backgroundColor: THEME.primary,
    borderColor: THEME.primary,
  },
  recurrenceTypeText: {
    fontSize: 14,
    fontWeight: "500",
    color: THEME.textDark,
    marginLeft: 4,
  },
  recurrenceTypeTextSelected: {
    color: THEME.textWhite,
  },
  recurrenceOptionsContainer: {
    marginTop: 12,
  },
  recurrenceOption: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  recurrenceOptionLabel: {
    fontSize: 16,
    color: THEME.textDark,
    marginRight: 8,
  },
  intervalContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  intervalInput: {
    backgroundColor: THEME.cardBg,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    width: 60,
    borderWidth: 1,
    borderColor: THEME.divider,
    marginRight: 8,
    fontSize: 16,
    color: THEME.textDark,
  },
  daysContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 8,
  },
  dayButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: THEME.cardBg,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 6,
    borderWidth: 1,
    borderColor: THEME.divider,
  },
  dayButtonSelected: {
    backgroundColor: THEME.primary,
    borderColor: THEME.primary,
  },
  dayText: {
    fontSize: 14,
    fontWeight: "500",
    color: THEME.textDark,
  },
  dayTextSelected: {
    color: THEME.textWhite,
  },
  recurrenceUntilContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: THEME.pageBg,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: THEME.divider,
  },
  formActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 24,
  },
  formButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  cancelButton: {
    backgroundColor: THEME.neutral100,
    marginRight: 10,
  },
  submitButton: {
    backgroundColor: THEME.primary,
    marginLeft: 10,
  },
  deleteButton: {
    backgroundColor: THEME.error,
    marginTop: 16,
  },
  buttonText: {
    fontSize: 16,
    fontWeight: "600",
  },
  cancelButtonText: {
    color: THEME.textDark,
  },
  submitButtonText: {
    color: THEME.textWhite,
  },
  deleteButtonText: {
    color: THEME.textWhite,
  },
  imagePickerContainer: {
    justifyContent: "center",
    padding: 16,
    backgroundColor: THEME.pageBg,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: THEME.divider,
  },
  imagePreview: {
    width: "100%",
    height: 200,
    borderRadius: 8,
    marginTop: 12,
  },
  // Image Viewer
  imageViewerContainer: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.9)",
    justifyContent: "center",
    alignItems: "center",
  },
  imageViewerCloseButton: {
    position: "absolute",
    top: 40,
    right: 20,
    zIndex: 100,
    padding: 10,
  },
  fullImage: {
    width: width * 0.9,
    height: height * 0.7,
  },
  // Church selector
  churchSelectorContainer: {
    marginBottom: 16,
  },
  selectorLabel: {
    fontSize: 16,
    fontWeight: "500",
    color: THEME.textDark,
    marginBottom: 8,
    paddingHorizontal: 20,
  },
  churchSelector: {
    flexDirection: "row",
    paddingHorizontal: 20,
  },
  churchOption: {
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: THEME.pageBg,
    marginRight: 8,
    borderWidth: 1,
    borderColor: THEME.divider,
  },
  churchOptionActive: {
    backgroundColor: THEME.primary,
    borderColor: THEME.primary,
  },
  churchOptionText: {
    color: THEME.textDark,
    fontSize: 14,
    fontWeight: "500",
    paddingVertical: 8,
  },
  churchOptionTextActive: {
    color: THEME.textWhite,
  },
  mainContent: {
    flex: 1,
    backgroundColor: THEME.pageBg,
  },
});
